# Gradle Memory Settings
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

org.gradle.java.home=/home/ptphong/.gradle/jdks/eclipse_adoptium-25-amd64-linux.2

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.1.2
mc_version_suffix=mc26.2.x
minecraft_dependency=>=26.2.0- <26.3.0
neoforge_version=26.2.0.45-beta
maven_group=com.drinfonty.redfx

# Dependencies
fabric_api_version=0.154.0+26.2

# Modrinth Automation
modrinth_project_id=uzc1jr0I
modrinth_game_versions=26.2
