# Gradle Memory Settings
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

org.gradle.java.home=/home/ptphong/.gradle/jdks/eclipse_adoptium-25-amd64-linux.2

# Fabric Properties
minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.14.10

# Mod Properties
mod_version=1.1.2
mc_version_suffix=mc1.21.x
minecraft_dependency=>=1.21.0 <1.22.0
neoforge_version=21.11.45
maven_group=com.drinfonty.redfx

# Dependencies
fabric_api_version=0.141.4+1.21.11

# Modrinth Automation
modrinth_project_id=uzc1jr0I
modrinth_game_versions=1.20.5,1.20.6,1.21,1.21.1
