plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	compileOnly "org.spongepowered:mixin:0.8.7"
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}
