modLoader="javafml"
loaderVersion="[1,)"
displayURL="https://modrinth.com/mod/redfx-blood-particle"
issueTrackerURL="https://github.com/Drinfonty/RedFX/issues"
license="CC0-1.0"

[[mods]]
modId="redfx"
version="${modVersion}"
displayName="RedFX"
description="A blood particle and visual effects mod."
authors="Drinfonty"

[[dependencies.redfx]]
modId="neoforge"
type="required"
versionRange="[26.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.redfx]]
modId="minecraft"
type="required"
versionRange="${minecraftDependency}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="redfx.mixins.json"

[[mixins]]
config="redfx.client.mixins.json"
